/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedZukanRouteImport } from './routes/_authed/zukan'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedRecordsIndexRouteImport } from './routes/_authed/records/index'
import { Route as AuthedRecordsNewRouteImport } from './routes/_authed/records/new'
import { Route as AuthedRecordsRecordIdEditRouteImport } from './routes/_authed/records/$recordId/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedZukanRoute = AuthedZukanRouteImport.update({
  id: '/zukan',
  path: '/zukan',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRecordsIndexRoute = AuthedRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRecordsNewRoute = AuthedRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRecordsRecordIdEditRoute =
  AuthedRecordsRecordIdEditRouteImport.update({
    id: '/records/$recordId/edit',
    path: '/records/$recordId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthedHomeRoute
  '/zukan': typeof AuthedZukanRoute
  '/records/new': typeof AuthedRecordsNewRoute
  '/records/': typeof AuthedRecordsIndexRoute
  '/records/$recordId/edit': typeof AuthedRecordsRecordIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthedHomeRoute
  '/zukan': typeof AuthedZukanRoute
  '/records/new': typeof AuthedRecordsNewRoute
  '/records': typeof AuthedRecordsIndexRoute
  '/records/$recordId/edit': typeof AuthedRecordsRecordIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/zukan': typeof AuthedZukanRoute
  '/_authed/records/new': typeof AuthedRecordsNewRoute
  '/_authed/records/': typeof AuthedRecordsIndexRoute
  '/_authed/records/$recordId/edit': typeof AuthedRecordsRecordIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/creator'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/home'
    | '/zukan'
    | '/records/new'
    | '/records/'
    | '/records/$recordId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creator'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/home'
    | '/zukan'
    | '/records/new'
    | '/records'
    | '/records/$recordId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/contact'
    | '/creator'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authed/home'
    | '/_authed/zukan'
    | '/_authed/records/new'
    | '/_authed/records/'
    | '/_authed/records/$recordId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/zukan': {
      id: '/_authed/zukan'
      path: '/zukan'
      fullPath: '/zukan'
      preLoaderRoute: typeof AuthedZukanRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/records/': {
      id: '/_authed/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AuthedRecordsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/records/new': {
      id: '/_authed/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof AuthedRecordsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/records/$recordId/edit': {
      id: '/_authed/records/$recordId/edit'
      path: '/records/$recordId/edit'
      fullPath: '/records/$recordId/edit'
      preLoaderRoute: typeof AuthedRecordsRecordIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedZukanRoute: typeof AuthedZukanRoute
  AuthedRecordsNewRoute: typeof AuthedRecordsNewRoute
  AuthedRecordsIndexRoute: typeof AuthedRecordsIndexRoute
  AuthedRecordsRecordIdEditRoute: typeof AuthedRecordsRecordIdEditRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedZukanRoute: AuthedZukanRoute,
  AuthedRecordsNewRoute: AuthedRecordsNewRoute,
  AuthedRecordsIndexRoute: AuthedRecordsIndexRoute,
  AuthedRecordsRecordIdEditRoute: AuthedRecordsRecordIdEditRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
